# Generated by Django 3.1.5 on 2021-06-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NEPS', models.CharField(blank=True, max_length=200, null=True)),
                ('NRQPS', models.CharField(blank=True, max_length=200, null=True)),
                ('processo', models.CharField(blank=True, max_length=200, null=True)),
                ('processo_soldagem', models.CharField(blank=True, max_length=200, null=True)),
                ('posicao_soldagem', models.CharField(blank=True, max_length=200, null=True)),
                ('especificacao', models.CharField(blank=True, max_length=200, null=True)),
                ('PN', models.IntegerField(default=0)),
                ('faixa_esp', models.CharField(blank=True, max_length=200, null=True)),
                ('faixa_diam', models.CharField(blank=True, max_length=200, null=True)),
                ('especificacao_metal_ad', models.CharField(blank=True, max_length=200, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=200, null=True)),
                ('FN', models.IntegerField(default=0)),
                ('qrcode', models.ImageField(null=True, upload_to='produtos')),
            ],
        ),
    ]
