# Generated by Django 3.1.5 on 2021-06-16 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eps',
            old_name='processo_soldagem',
            new_name='progressao_soldagem',
        ),
    ]
