# Generated by Django 3.1.5 on 2021-06-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210616_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soldadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinete', models.CharField(blank=True, max_length=200, null=True)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('EPS', models.CharField(blank=True, max_length=200, null=True)),
                ('processo', models.CharField(blank=True, max_length=200, null=True)),
                ('modo_trensferencia', models.CharField(blank=True, max_length=200, null=True)),
                ('FN', models.IntegerField(default=0)),
                ('metal_base', models.CharField(blank=True, max_length=200, null=True)),
                ('esp_chanfro', models.CharField(blank=True, max_length=200, null=True)),
                ('esp_angulo', models.CharField(blank=True, max_length=200, null=True)),
                ('diametro_chanfro', models.CharField(blank=True, max_length=200, null=True)),
                ('diametro_angulo', models.CharField(blank=True, max_length=200, null=True)),
                ('posiçao', models.CharField(blank=True, max_length=200, null=True)),
                ('progressao_soldagem', models.CharField(blank=True, max_length=200, null=True)),
                ('cobre_junta', models.CharField(blank=True, max_length=200, null=True)),
                ('notas', models.CharField(blank=True, max_length=200, null=True)),
                ('qrcode', models.ImageField(null=True, upload_to='soldador')),
                ('validade', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
