# Generated by Django 3.1.5 on 2021-06-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_soldadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eps',
            name='qrcode',
            field=models.ImageField(null=True, upload_to='core\\static\\core\\dist\\img'),
        ),
        migrations.AlterField(
            model_name='soldadores',
            name='qrcode',
            field=models.ImageField(null=True, upload_to='core\\static\\core\\dist\\img'),
        ),
    ]
