# Generated by Django 3.1.5 on 2021-08-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210616_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldadores',
            name='dados',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
