# Generated by Django 3.1.5 on 2021-08-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_soldadores_dados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldadores',
            name='dados',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
